services:
  postgres:
    image: postgres
    container_name: postgres_beneficios
    restart: always
    environment:
      POSTGRES_USER: beneficios_user
      POSTGRES_PASSWORD: beneficios_pass
      POSTGRES_DB: beneficios_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
