services:
  postgres:
    image: postgres
    container_name: postgres_beneficios
    restart: always
    environment:
      POSTGRES_USER: beneficios_user
      POSTGRES_PASSWORD: beneficios_pass
      POSTGRES_DB: beneficios_db
    ports:
      - "5434:5432"
    networks:
      - shared_network

    volumes:
      - postgres_data:/var/lib/postgresql/data



  api:
    build:
      context: . # pasta que contém o Dockerfile
    container_name: beneficios-api
    ports:
      - "8087:8087"
    networks:
      - shared_network

    depends_on:
      - postgres
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/beneficios_db
      POSTGRES_USER: beneficios_user
      POSTGRES_PASSWORD: beneficios_pass
      POSTGRES_DB: beneficios_db




networks:
  shared_network:
    external: true


volumes:
  postgres_data:


